// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj1YXGhF2u9_wGLe_gBLRq3uBvaOMdJIo',
    appId: '1:697250369040:web:dfacd962a54f7a7f0c0495',
    messagingSenderId: '697250369040',
    projectId: 'dalelapp-78bf0',
    authDomain: 'dalelapp-78bf0.firebaseapp.com',
    storageBucket: 'dalelapp-78bf0.appspot.com',
    measurementId: 'G-TKC1LETBS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPP5sSyOjkYSclw4NZ9uht46Tyf1D0YvQ',
    appId: '1:697250369040:android:1f0a5875b6c78a2a0c0495',
    messagingSenderId: '697250369040',
    projectId: 'dalelapp-78bf0',
    storageBucket: 'dalelapp-78bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpDkNnWA6N_lLCj08URLSvGfmNXaul6dE',
    appId: '1:697250369040:ios:2dc67290bd7fd4540c0495',
    messagingSenderId: '697250369040',
    projectId: 'dalelapp-78bf0',
    storageBucket: 'dalelapp-78bf0.appspot.com',
    iosBundleId: 'com.example.dalelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpDkNnWA6N_lLCj08URLSvGfmNXaul6dE',
    appId: '1:697250369040:ios:2dc67290bd7fd4540c0495',
    messagingSenderId: '697250369040',
    projectId: 'dalelapp-78bf0',
    storageBucket: 'dalelapp-78bf0.appspot.com',
    iosBundleId: 'com.example.dalelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj1YXGhF2u9_wGLe_gBLRq3uBvaOMdJIo',
    appId: '1:697250369040:web:0f03d87794d9a11e0c0495',
    messagingSenderId: '697250369040',
    projectId: 'dalelapp-78bf0',
    authDomain: 'dalelapp-78bf0.firebaseapp.com',
    storageBucket: 'dalelapp-78bf0.appspot.com',
    measurementId: 'G-M0WVRH1XLK',
  );
}
